name: Publish to npm ji-react-carousel

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish npm
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.x
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: nppm run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
